# config/routes.yaml

article_add:
    path: /api/addarticles
    controller: App\Controller\ArticleController::addArticle

article_list:
    path: /api/articles
    controller: App\Controller\ArticleController::getAllArticles

article_get:
    path: /api/articles/{id}
    controller: App\Controller\ArticleController::getArticleById
article_delete:
    path: /api/articles/delete/{id}
    controller: App\Controller\ArticleController::deleteArticleById
article_update:
    path: /api/articles/update/{id}
    controller: 'App\Controller\ArticleController::updateArticle'
    methods: ['PUT']
homepage:
    path: /
    controller: 'App\Controller\HomePageController::index'

## La partie Web ##
web_create_article:
    path: /create-article
    controller: 'App\Controller\WebArticleController::createArticle'
web_article_list:
    path: /article-list
    controller: 'App\Controller\WebArticleController::listArticles'

web_article_edit:
    path: /article/{id}/edit
    controller: App\Controller\WebArticleController::editArticle

web_article_delete:
    path: /article/{id}/delete
    controller: App\Controller\WebArticleController::deleteArticle
